//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DotPhatHanh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DotPhatHanh()
        {
            this.CauHinhPMHs = new HashSet<CauHinhPMH>();
        }
    
        public int idDPH { get; set; }
        public string tenDPH { get; set; }
        public Nullable<int> idLoai { get; set; }
        public Nullable<int> idDVPH { get; set; }
        public string dienGiai { get; set; }
        public Nullable<int> trangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CauHinhPMH> CauHinhPMHs { get; set; }
        public virtual DonViPhatHanh DonViPhatHanh { get; set; }
        public virtual LoaiPhatHanh LoaiPhatHanh { get; set; }
    }
}
