//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class internShipEntities : DbContext
    {
        public internShipEntities()
            : base("name=internShipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<nhom> nhoms { get; set; }
        public virtual DbSet<phanLoaiNhom> phanLoaiNhoms { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<CauHinhPMH> CauHinhPMHs { get; set; }
        public virtual DbSet<DonViApDung> DonViApDungs { get; set; }
        public virtual DbSet<DonViPhatHanh> DonViPhatHanhs { get; set; }
        public virtual DbSet<DotPhatHanh> DotPhatHanhs { get; set; }
        public virtual DbSet<LoaiPhatHanh> LoaiPhatHanhs { get; set; }
        public virtual DbSet<PMH> PMHs { get; set; }
        public virtual DbSet<PMH_ApDung> PMH_ApDung { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
