//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phanLoaiNhom
    {
        public int idPhanLoai { get; set; }
        public Nullable<int> idNhom { get; set; }
        public string tenPhanLoaiNhom { get; set; }
    
        public virtual nhom nhom { get; set; }
    }
}
